package com.d18sg.flowctrl;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class FlowctrlApplicationTests {

	/*
	 *From https://docs.spring.io/spring-shell/docs/current/reference/htmlsingle/#_getting_started
	 * 	Given that Spring Shell starts the REPL (Read-Eval-Print-Loop) because this dependency is present, you need to either skip tests when you build (-DskipTests)
	 * 	throughout this tutorial or remove the sample integration test that was generated by start.spring.io.
	 * 	If you do not remove it, the integration test creates the Spring ApplicationContext and, depending on your build tool, stays stuck in the eval loop or crashes with a NPE.
	 */
	//@Test
	void contextLoads() {
	}

}
